GET http://127.0.0.1:8000/api/users?limit=10&page=1&q=
Accept: application/json
Authorization: Bearer 6|bHnc5PSxUE8XqfQa4m79rHg3zBFDCWM8XWKcn7Xh

### Guardar usuario
POST http://127.0.0.1:8000/api/users
Accept: application/json
Content-Type: application/json
Authorization: Bearer 6|bHnc5PSxUE8XqfQa4m79rHg3zBFDCWM8XWKcn7Xh

{
    "name": "Juan",
    "email": "juan2@mail.com",
    "password": "juan54321"
}

### mostrar
GET http://127.0.0.1:8000/api/users/1
Accept: application/json
Authorization: Bearer 6|bHnc5PSxUE8XqfQa4m79rHg3zBFDCWM8XWKcn7Xh

### Modificar usuario
PUT http://127.0.0.1:8000/api/users/3
Accept: application/json
Content-Type: application/json
Authorization: Bearer 6|bHnc5PSxUE8XqfQa4m79rHg3zBFDCWM8XWKcn7Xh

{
    "name": "Juan Modificado",
    "email": "juan@mail2.com"
}

### eliminar
DELETE http://127.0.0.1:8000/api/users/3
Accept: application/json
Authorization: Bearer 6|bHnc5PSxUE8XqfQa4m79rHg3zBFDCWM8XWKcn7Xh